/**
 * Golden snapshot regression test — freezes the full normalized KundliData
 * output for the three reference charts. Any unintended change to any field
 * fails CI with a readable diff.
 *
 * Baselines live in __golden__/{dev,rajiv,amitabh}.ts and are generated by:
 *   deno run --allow-write=supabase/functions/calculate-kundli/__golden__ scripts/update-golden.ts
 *
 * Intended workflow when a future PR *intentionally* changes engine output:
 *   1. Re-run the updater script to refresh the baselines.
 *   2. Eyeball `git diff __golden__/` to confirm the change is expected.
 *   3. Bump CURRENT_SNAPSHOT_VERSION in both types.ts and engine.ts.
 *
 * No file/env reads at runtime — baselines are static imports, so this test
 * runs under the existing permissionless CI command (no --allow-read needed).
 */

import { assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { calculateKundli } from "./engine.ts";
import {
  DEV_CHART,
  RAJIV_GANDHI,
  AMITABH_BACHCHAN,
  normalize,
} from "./__golden__/_shared.ts";
import { EXPECTED as DEV } from "./__golden__/dev.ts";
import { EXPECTED as RAJIV } from "./__golden__/rajiv.ts";
import { EXPECTED as AMITABH } from "./__golden__/amitabh.ts";

for (const [name, fixture, expected] of [
  ["Dev Chart", DEV_CHART, DEV],
  ["Rajiv Gandhi", RAJIV_GANDHI, RAJIV],
  ["Amitabh Bachchan", AMITABH_BACHCHAN, AMITABH],
] as const) {
  Deno.test(`Golden: full KundliData — ${name}`, async () => {
    const actual = normalize(await calculateKundli(fixture));
    assertEquals(actual, expected); // deep structural equality → readable diff on drift
  });
}
