/**
 * Golden baseline updater — regenerates the __golden__/*.ts baseline modules
 * from the current engine output.
 *
 * Usage (local only — never runs in CI):
 *   deno run --allow-write=supabase/functions/calculate-kundli/__golden__ scripts/update-golden.ts
 *
 * Intended workflow:
 *   When a future PR *intentionally* changes engine output, the author:
 *     1. Re-runs this updater to refresh the baselines.
 *     2. Eyeballs `git diff __golden__/` to confirm the change is expected.
 *     3. Bumps CURRENT_SNAPSHOT_VERSION in both types.ts and engine.ts.
 *   The golden test is the machine-checkable companion to that version bump.
 */

import { calculateKundli } from "../supabase/functions/calculate-kundli/engine.ts";
import {
  DEV_CHART,
  RAJIV_GANDHI,
  AMITABH_BACHCHAN,
  normalize,
} from "../supabase/functions/calculate-kundli/__golden__/_shared.ts";

const GOLDEN_DIR = "supabase/functions/calculate-kundli/__golden__";

const charts: Array<{ name: string; file: string; fixture: typeof DEV_CHART }> = [
  { name: "Dev Chart", file: "dev.ts", fixture: DEV_CHART },
  { name: "Rajiv Gandhi", file: "rajiv.ts", fixture: RAJIV_GANDHI },
  { name: "Amitabh Bachchan", file: "amitabh.ts", fixture: AMITABH_BACHCHAN },
];

for (const { name, file, fixture } of charts) {
  console.log(`Generating baseline for ${name}…`);
  const kundli = await calculateKundli(fixture);
  const normalized = normalize(kundli);
  const json = JSON.stringify(normalized, null, 2);
  const content = `// Auto-generated by scripts/update-golden.ts — do not hand-edit.\nexport const EXPECTED = ${json} as const;\n`;
  const path = `${GOLDEN_DIR}/${file}`;
  await Deno.writeTextFile(path, content);
  console.log(`  → wrote ${path}`);
}

console.log("Done. Run the golden test to verify:\n  deno test supabase/functions/calculate-kundli/engine_golden_test.ts");
