import { registerSW } from "virtual:pwa-register";
import { toast } from "@/components/ui/sonner";

/**
 * Registers the service worker (generated by vite-plugin-pwa) and wires the
 * `prompt` update flow into a Sonner toast.
 *
 * Called only in production from main.tsx via a dynamic import, so the
 * `virtual:pwa-register` module never enters the dev/test module graph.
 */
export function registerPwa(): void {
  const updateSW = registerSW({
    onNeedRefresh() {
      // A new service worker is waiting (registerType: "prompt"). Ask the user
      // to reload rather than swapping the bundle out from under an open chart.
      toast("A new version of Acharya Jyotish is available.", {
        duration: Infinity,
        action: {
          label: "Reload",
          onClick: () => updateSW(true), // activate the waiting SW, then reload
        },
      });
    },
    onOfflineReady() {
      toast.success("Acharya Jyotish is ready to work offline.");
    },
  });
}
